### ISSUE TITLE
Artifactory Tools Installer Task 1.10.3 throws error, 1.10.2 does not

### ISSUE THREAD

**Issue by Thacai** [jfrog/artifactory-azure-devops-extension#205] opened 2020-09-30 16:30 UTC
**Describe the bug**
Ran my pipeline twice today, now throws error Error: Cannot find module 'azure-pipelines-task-lib/task'

**To Reproduce**
Run Artifactory Tools Installer Task
**Expected behavior**
No errors thrown, same as 1.10.2

**Screenshots**
Error (1.10.3):
![image](https://user-images.githubusercontent.com/4174649/94712359-ae7f3400-0349-11eb-854a-c0f4a5cda83d.png)
Working (1.10.2)
![image](https://user-images.githubusercontent.com/4174649/94712414-c0f96d80-0349-11eb-9af5-b972de194e5a.png)

Source:
![image](https://user-images.githubusercontent.com/4174649/94713399-04a0a700-034b-11eb-8314-4c33e4f798b5.png)

**Versions**
- Artifactory Azure DevOps extension version: 1.10.3
- Agent operating system: Windows 10
- JFrog Artifactory version: 6.18.1

**Additional context**
Working timestamp: 2020-09-30T09:05:16 UTC+2
Error timestamp: 2020-09-30T16:08:17 UTC+2

**Comment by AKRSafe** [comment] 2020-09-30 16:47
I could see the same happening with 1.10.4 as well.

**Comment by Thacai** [comment] 2020-09-30 16:49
> I could see the same happening with 1.10.4 as well.

I pinned it to 1.10.2 as we're in the middle of getting a release out, atleast until it's confirmed to be resolved

**Comment by AceHack** [comment] 2020-09-30 16:50
How do you pin it in Azure Dev Ops?

**Comment by AceHack** [comment] 2020-09-30 16:51
We are getting this error over and over in our builds.

**Comment by eyalbe4** [comment] 2020-09-30 16:51
@Thacai and @AceHack,
We're working on resolving this issue ASAP.
We'll send out an update soon.

**Comment by AceHack** [comment] 2020-09-30 16:52
FYI, make sure you guys are running npm install before publishing your task.
https://github.com/microsoft/azure-pipelines-task-lib/issues/485

**Comment by Thacai** [comment] 2020-09-30 16:52
yaml you can pin it like:`- task: ArtifactoryToolsInstaller@1.10.2`

Can't remember if you can pin the minor/patch version on classic pipelines

> How do you pin it in Azure Dev Ops?

**Comment by AceHack** [comment] 2020-09-30 16:54
This is happening for me in ArtifactoryGenericUpload@2
What should I pin that to?

**Comment by AceHack** [comment] 2020-09-30 16:54
Where can I find these version numbers

**Comment by Thacai** [comment] 2020-09-30 16:55
I just found the previous version by looking at the previous pipeline output:
![image](https://user-images.githubusercontent.com/4174649/94715984-7c240580-034e-11eb-9cd4-346fd5aff585.png)

**Comment by mrgandra** [comment] 2020-09-30 16:56
Only in Yaml you can pin it. But in UI you cant

**Comment by RobiNino** [comment] 2020-09-30 17:01
Version 1.10.5 was now released and the issue was fixed.
Please refresh or reinstall the extension if it doesn't automatically update.
We are incredibly sorry about the inconvenience caused by this issue.

**Closed by RobiNino** 2020-09-30 17:01 UTC
Labels: bug

**Comment by eyalbe4** [comment] 2020-10-01 14:35
Thanks you all for sharing this information.
I've just added a comment in https://github.com/jfrog/artifactory-azure-devops-extension/issues/207 summarising the issue. If needed, let's continue the discussion there.
