### ISSUE TITLE
Error: unable to get local issuer certificate - New version 1.11.1

### ISSUE THREAD

**Issue by bcouavoux** [jfrog/artifactory-azure-devops-extension#223] opened 2020-12-21 10:11 UTC
**Describe the bug**
Since the last version of the task in 1.11.1, all our pipelines crash with the error "Error: unable to get local issuer certificate" when the task try to download the jfrog cli exe. We didn't have this error before the update.. The env var NODE_EXTRA_CA_CERTS is well informed and we can download the jfrog cli exe manually on the agents.

**Screenshots**
Starting: Artifactory NuGet restore métier
Task         : Artifactory Nuget
Description  : Restore and push NuGet packages from and to Artifactory while allowing to collect build-info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build Info" task.
Version      : 1.11.1
Author       : JFrog
Help         : [More Information](https://www.jfrog.com/confluence/display/RTF/NuGet+Repositories)
Downloading: https://api.bintray.com/content/jfrog/jfrog-cli-go/1.42.2/jfrog-cli-windows-amd64/jfrog.exe?bt_package=jfrog-cli-windows-amd64
##[error]Error occurred while executing task:
Failed while attempting to download JFrog CLI from https://api.bintray.com/content/jfrog/jfrog-cli-go/1.42.2/jfrog-cli-windows-amd64/jfrog.exe?bt_package=jfrog-cli-windows-amd64. If this build agent cannot access the internet, you may use the 'Artifactory Tools Installer' task, to download JFrog CLI through an Artifactory repository, which proxies 
Error: unable to get local issuer certificate
Finishing: Artifactory NuGet restore métier

**Versions**
- Artifactory Azure DevOps extension version: 1.11.1
- Agent operating system: WS 2019

**Comment by eyalbe4** [comment] 2020-12-21 10:52
@bcouavoux - thanks for reporting this!
I can't think of anything that that changed on 1.11.1 vs. 1.11.0. You can see the code all the code that chanegd [here](https://github.com/jfrog/artifactory-azure-devops-extension/commits/master). I wonder if anyone else experienced such an issue.

**Comment by bcouavoux** [comment] 2020-12-21 13:14
Ok thanks so where could it come from?
I see that the new version call a new version of jfrog cli (1.42.2) that is not present in our agent tools folder and the task can't download it .. The agent has full access to internet and we can download it via the url on a web browser directly on the same agent.
The NODE_EXTRA_CA_CERTS var env is also well informed, so I really don't understand where the problem comes from

**Comment by bcouavoux** [comment] 2020-12-21 13:29
And we never had a problem downloading the previous versions :
![image](https://user-images.githubusercontent.com/52322253/102781977-d86c5380-4398-11eb-838d-789d796d046d.png)

**Comment by bcouavoux** [comment] 2020-12-21 14:53
We are going to use the task "ArtifactoryToolsInstaller" that recovered from our private repo the latest version of jfrog cli before the retore task :

![image](https://user-images.githubusercontent.com/52322253/102787715-ce028780-43a1-11eb-9516-982d950efee6.png)

I just dont understand why the "Artifactory NuGet restore" cant recovered from bintray but anyway you can close the ticket

**Comment by eyalbe4** [comment] 2020-12-21 19:47
@bcouavoux - 
I'm actually really curious about the cause of this issue. I'm closing this issue now, but if you manage to figure out the cause, it'll be great if you shared it.

**Closed by eyalbe4** 2020-12-21 19:47 UTC
Labels: bug
